core_app/urls.py
from . import views as base_views
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
	path('', base_views.home_view, name='home'),
	path('contact/', base_views.contact_view, name='contact'),
	path('about/', base_views.about_view, name='about'),
    path('terms_and_condition/', base_views.TermsAndConditionView.as_view(), name='terms_and_condition'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('core_app.urls')),
    path('posts/', include('post_app.urls')),
    path('users/', include('user_app.urls')),
]

post_app/urls.py
from . import views as base_views
from django.urls import path
from post_app import views as post_views
from django.contrib.auth import views as auth_views

urlpatterns = [
	path('create_post/', post_views.create_post, name='create_post'),
    path('post_detail/<int:pk>/', post_views.post_detail, name='post_detail'),
]

user_app/urls.py
from django.urls import path
from user_app import views as user_views
from django.contrib.auth import views as auth_views
from .views import login_view

urlpatterns = [
	path('profile/', user_views.profile_view, name='profile'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),	
	path('login/', login_view, name='login'),
]

core_app/models.py
from django.shortcuts import render
from post_app.views import Post

def home(request):
    posts = Post.objects.all()
    return render(request, 'home.html', {'posts': posts})

post_app/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

POST_THEME = ['']

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE, related_name='blog_posts')
    theme = models.CharField(max_length=50, choices=[
        ('technology', 'Technology'),
        ('science', 'Science'),
        ('travel', 'Travel'),
        ('finance', 'Finance'),
        ('relationships', 'Relationships'),
        ('beauty', 'Beauty'),
        ('fashion', 'Fashion'),
        ('education', 'Education'),
        ('healthy', 'Healthy')
    ], blank=True)
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.IntegerField(default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

user_app/models.py
from django.db import models


class User(models.Model):
	pass

core_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label=("Email"))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

post_app/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
	
	class Meta:
		model = Post
		fields = ['title', 'content', 'theme']

core_app/views.py
from django.views import generic
from django.shortcuts import render, redirect
from post_app.models import Post
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


FIELD_FOR_SORTING_MAP = {
    'Likes': 'likes',
    'Time':'-created_on'
}


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  # Log in the user after registration
            return redirect('home')  # Redirect to the home page or any desired page
        else:
            print(form.errors)
            print("Your form is not correct")
    else:
        print("Not post method")
        form = UserCreationForm()
    return render(request, 'registration.html', {'form': form})

def about_view(request):
    # Your view logic goes here
    return render(request, 'about.html') 

def contact_view(request):
    return render(request, 'contact.html')


def picked_theme(request):
    print(request.GET)
    if 'theme' in request.GET:
        return request.GET.get('theme')
    else:
        return False

def home_view(request):
    theme = picked_theme(request)
    print(theme)
    if theme:
        posts = Post.objects.filter(theme=theme)
    else:
        posts = Post.objects.all()

    # Get the selected sorting options from the request
    selected_sort = request.GET.getlist('sort_by', default=['Time'])

    # Validate selected_sort to avoid potential security risks
    selected_sort = [option for option in selected_sort if option in FIELD_FOR_SORTING_MAP]

    # Apply sorting to posts based on the selected options
    posts = posts.order_by(FIELD_FOR_SORTING_MAP[selected_sort[0]])

    available_themes = Post._meta.get_field('theme').choices

    themes = [theme[1] for theme in available_themes]

    context = {
        'posts': posts,
        'sort_options': FIELD_FOR_SORTING_MAP.keys(),
        'selected_sort': selected_sort,
        'themes': themes
    }
    return render(request, 'home.html', context)

class TermsAndConditionView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'terms_and_condition.html')

post_app/views.py
from django.views import generic
from django.shortcuts import render, redirect
from post_app.models import Post
from django.contrib.auth.decorators import login_required
from .forms import PostForm
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect



class PostList(generic.ListView):
	queryset = Post.objects.filter(status=1).order_by('-created_on')
	template_name = 'home.html'
	
	def render_to_response(self, context, **response_kwargs):
		print(context)  # Add this line to print context
		return super().render_to_response(context, **response_kwargs)


@login_required
def create_post(request):
	if request.method == 'POST':
		form = PostForm(request.POST)
		if form.is_valid():
			# Create a new post object but don't save it yet
			new_post = form.save(commit=False)
			new_post.author = request.user  # Set the author to the currently logged-in user
			new_post.save()  # Now save the post with the author information
			return redirect('profile')  # Redirect to the home page or post list page
	else:
		form = PostForm()


	return render(request, 'create_post.html', {'form': form})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # Check if the user has already liked the post
    liked_before = request.session.get(f'post_{pk}_liked', False)

    if request.method == 'POST' and not liked_before:
        # Check if the like button is clicked
        if 'like_button' in request.POST:
            post.likes += 1
            post.save()

            # Set a session variable to indicate that the user has liked the post
            request.session[f'post_{pk}_liked'] = True

            return HttpResponseRedirect(request.path)

    return render(request, 'post_detail.html', {'post': post, 'liked_before': liked_before})


	

user_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

@login_required
def profile_view(request):
    current_user = request.user
    username = current_user.username
    email = current_user.email

    return render(request, 'profile.html', {'username': username, 'email': email})


def login_view(request):
    return render(request, 'login.html')

blog_site/blog/templates/registration.html
<!DOCTYPE html>
<!-- Coding By CodingNepal - codingnepalweb.com -->
<html lang="en" dir="ltr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> Registration or Sign Up form in HTML CSS | CodingLab </title> 
  <link rel="stylesheet" href="static/style.css">
</head>
<body>
  <div class="wrapper">
    <h2>Registration</h2>
    <form method="post" action="{% url 'register' %}">
        {% csrf_token %} 
      <!-- Display error messages -->
      <div class="error-message">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="error">{{ error }}</div>
                {% endfor %}
            {% endfor %}
        {% endif %}
      </div>

      <div class="input-box">
        <label for="id_name">Username:</label>
        <input type="text" id="id_name" name="username" placeholder="Enter your username" required>
      </div>
      <div class="input-box">
        <label for="id_email">Email:</label>
        <input type="text" id="id_email" name="email" placeholder="Enter your email" required>
      </div>
      <div class="input-box">
        <label for="id_password">Password:</label>
        <input type="password" id="id_password" name="password1" placeholder="Create password" required>
      </div>
      <div class="input-box">
        <label for="id_confirm_password">Confirm Password:</label>
        <input type="password" id="id_confirm_password" name="password2" placeholder="Confirm password" required>
      </div>
      <div class="policy">
        <span class="checkbox-wrapper">
          <input type="checkbox" id="id_agree" name="agree" required>
        </span>
        <label for="id_agree">I accept all <a href="{% url 'terms_and_condition' %}">terms & conditions</a></label>
      </div>      
      <div class="input-box button">
        <input type="submit" value="Register Now">
      </div>
      <div class="text">
        <h3>Already have an account? <a href="#">Login now</a></h3>
      </div>
    </form>
  </div>
</body>
</html>

core_app/templates/about.html
<!-- about.html -->

{% extends 'base.html' %}

{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'about.css' %}">
    
    <section class="project-description">
        <h1>About My Project</h1>
        <p>
            Welcome to my project! This project is a personal blog site developed with Django, showcasing my skills in web development.
            It includes features such as a homepage displaying blog posts, a registration system, and more.
        </p>
    </section>

{% endblock %}

core_app/templates/base.html
<!-- base.html -->


{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <title>{% block title %}My Blog{% endblock %}</title>
    {% block head %}{% endblock %}
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'contact' %}">Contact</a></li>
                <li class="profile-button">
                    <a href="{% url 'profile' %}">
                        <span class="profile-icon">
                            <div class="profile-link"></div>
                            {% if user.is_authenticated %}
                                {{ user.username.0|upper }}
                            {% else %}
                                <!-- Default icon or letter for non-authenticated users -->
                                A
                            {% endif %}
                        </span>
                    </a>
                </li>
            </ul>
        </nav>
    </header>

    <section class="content">
        {% block content %}{% endblock %}
    </section>

    <footer>
        <p>&copy; 2024 My Blog. All rights reserved.</p>
    </footer>
</body>
</html>

core_app/templates/contact.html
<!-- contact.html -->


{% extends 'base.html' %}
{% load static %}
{% block title %}Contact Me{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'contact.css' %}">
    <section class="contact-info">
        <h1>Contact Me</h1>
        <p>
            You can reach out to me through various channels:
        </p>
        <ul>
            <li>
                LinkedIn: <a href="https://www.linkedin.com/in/vlad-maslianko-b4a885290/" target="_blank" rel="noopener noreferrer">Vlad Maslianko</a>
            </li>
            <li>
                GitHub: <a href="https://github.com/aunth" target="_blank" rel="noopener noreferrer">aunth</a>
            </li>
            <li>
                Telegram: <a href="https://t.me/vmaslian" target="_blank" rel="noopener noreferrer">@vmaslian</a>
            </li>
            <li>
                Email: <a href="mailto:masliankovlad@gmail.com">masliankovlad@gmail.com</a>
            </li>
        </ul>
    </section>
{% endblock %}

core_app/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}My Blog - Home{% endblock %}
{% block head %} <link rel="stylesheet" href="{% static 'home.css' %}"> {% endblock %}
{% block content %}
<!-- home.html -->
<form method="get" action="{% url 'home' %}" class="sort-form">
    <label>
        Sort by:
        {% for option in sort_options %}
            <input type="radio" name="sort_by" value="{{ option }}"
                   {% if option == selected_sort %} checked{% endif %}>
            {{ option|title }}
        {% endfor %}
    </label>
    
    <label>
        Filter by Theme:
        <select name="theme">
            <option value="" {% if not selected_theme %}selected{% endif %}>All Themes</option>
            {% for theme in themes %}
                <option value="{{ theme }}" {% if theme == selected_theme %}selected{% endif %}>{{ theme }}</option>
            {% endfor %}
        </select>
    </label>

    <button type="submit">Apply</button>
</form>

<section class="blog-posts">
    {% if selected_theme %}
        <p>Filtering by Theme: {{ selected_theme }}</p>
    {% endif %}
    {% if not posts %}
        <h1>No posts have been added</h1>
    {% else %}
        {% for post in posts %}
            <article class="blog-post">
                <h2>{{ post.title }}</h2>
                <p class="post-meta">{{ post.theme }}</p>
                <p class="post-content">{{ post.content }}</p>
                <p class="post-author">{{ post.author }}</p>
                <a href="{% url 'post_detail' post.id %}" class="read-more">Read More</a>
                {% with post.likes as likes_count %}
                        <span>&#x1F497;</span>
                        <span>{{ likes_count }}</span> 
                {% endwith %}
            </article>
        {% endfor %}
    {% endif %}
</section>

{% endblock %}

core_app/templates/index.html
{% extends "base.html" %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                    <p class="text-light">We Love Django As much as you do..! &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%endblock%}

core_app/templates/post_list.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 mt-3 left">
        {% for post in post_list %}
          <div class="card mb-4">
            <div class="card-body">
              <h2 class="card-title">{{ post.title }}</h2>
              <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on }}</p>
              <p class="card-text">{{ post.content|slice:":200" }}</p>
              <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Read More &rarr;</a>
            </div>
          </div>
        {% endfor %}
      </div>
      {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
  </div>
{% endblock %}

core_app/templates/terms_and_condition.html
<!DOCTYPE html>
<!-- Coding By CodingNepal - codingnepalweb.com -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms & Condition</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap">
    <link rel="stylesheet" href="../static/style.css">
  </head>
  <body>
    <div class="wrapper">
      <h2>If you accept our terms and conditions</h2>
      <p>It means that you should go to the East of Ukraine and defend our country.</p>
    </div>
  </body>
</html>

post_app/templates/create_post.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Post creating</title>
</head>
<body>

	<form method="post" action="{% url 'create_post' %}">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Submit</button>
	</form>
	
</body>
</html>

post_app/templates/post_detail.html
<!-- post_detail.html -->

{% extends 'base.html' %}

{% load static %}

{% block title %}{{ post.title }} - My Blog{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'post_detail.css' %}">
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>

    {% if not liked_before %}
        <!-- Like button form -->
        <form method="post" action="{% url 'post_detail' pk=post.pk %}">
            {% csrf_token %}
            <button type="submit" name="like_button">
                <span>&#x2665;</span> Like
            </button>
        </form>
    {% else %}
        <p>You have already liked this post!</p>
    {% endif %}

    <p>Likes: {{ post.likes }}</p>

    <a href="{% url 'home' %}">Back to Post List</a>
{% endblock %}

user_app/templates/login.html
<!DOCTYPE html>
<!-- Coding By CodingNepal - codingnepalweb.com -->
<html lang="en" dir="ltr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Log in</title> 
  <link rel="stylesheet" href="static/style.css">
</head>
<body>
  <div class="wrapper">
    <h2>Log in</h2>
    <form method="post" action="{% url 'register' %}">
        {% csrf_token %} 
      <!-- Display error messages -->
      <div class="error-message">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="error">{{ error }}</div>
                {% endfor %}
            {% endfor %}
        {% endif %}
      </div>
      <div class="input-box">
        <label for="id_email">Email:</label>
        <input type="text" id="id_email" name="email" placeholder="Enter your email" required>
      </div>
      <div class="input-box">
        <label for="id_password">Password:</label>
        <input type="password" id="id_password" name="password1" placeholder="Create password" required>
      </div>    
      <div class="input-box button">
        <input type="submit" value="Register Now">
      </div>
      <div class="text">
        <h3>Don't have an account? <a href="#">Registration now</a></h3>
      </div>
    </form>
  </div>
</body>
</html>

user_app/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <!-- Include profile.css only for this template -->
    <link rel="stylesheet" href="{% static 'profile.css' %}">
{% endblock %}

{% block content %}
    <h1>User Profile</h1>
    <p>Welcome, {{ username }}!</p>
    <p>Your email address: {{ email }} |</p>

    <a href="{% url 'logout' %}">Logout</a>
{% endblock %}

user_app/templates/registration.html
<!DOCTYPE html>
<!-- Coding By CodingNepal - codingnepalweb.com -->
<html lang="en" dir="ltr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> Registration or Sign Up form in HTML CSS | CodingLab </title> 
  <link rel="stylesheet" href="static/style.css">
</head>
<body>
  <div class="wrapper">
    <h2>Registration</h2>
    <form method="post" action="{% url 'register' %}">
        {% csrf_token %} 
      <!-- Display error messages -->
      <div class="error-message">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="error">{{ error }}</div>
                {% endfor %}
            {% endfor %}
        {% endif %}
      </div>

      <div class="input-box">
        <label for="id_name">Username:</label>
        <input type="text" id="id_name" name="username" placeholder="Enter your username" required>
      </div>
      <div class="input-box">
        <label for="id_email">Email:</label>
        <input type="text" id="id_email" name="email" placeholder="Enter your email" required>
      </div>
      <div class="input-box">
        <label for="id_password">Password:</label>
        <input type="password" id="id_password" name="password1" placeholder="Create password" required>
      </div>
      <div class="input-box">
        <label for="id_confirm_password">Confirm Password:</label>
        <input type="password" id="id_confirm_password" name="password2" placeholder="Confirm password" required>
      </div>
      <div class="policy">
        <span class="checkbox-wrapper">
          <input type="checkbox" id="id_agree" name="agree" required>
        </span>
        <label for="id_agree">I accept all <a href="{% url 'terms_and_condition' %}">terms & conditions</a></label>
      </div>      
      <div class="input-box button">
        <input type="submit" value="Register Now">
      </div>
      <div class="text">
        <h3>Already have an account?  <a href="{% url 'login' %}"></a>Login now</a></h3>
      </div>
    </form>
  </div>
</body>
</html>